name: Sync to FTP server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - uses: actions/checkout@v2
      
      
      -   name: Setup Node
          uses: actions/setup-node@v2
          with:
              node-version: '14'

      - name: Install node modules
        run: npm ci
      
      - name: Build CSS files
        run: |
          npm run build:xbone
          npm run build:ps4

      - name: Install lftp
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y lftp

      - name: Upload CSS file to FTP server
        run: |
          lftp -c 'set ssl:check-hostname no; open ${{ secrets.FTP_HOSTNAME }}; user ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASSWORD }}; put -O / ./build/pengaloni-ds4.min.css; quit'

      - name: Upload Xbone CSS file to FTP server
        run: |
          lftp -c 'set ssl:check-hostname no; open ${{ secrets.FTP_HOSTNAME }}; user ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASSWORD }}; put -O / ./build/pengaloni-xbone.min.css; quit'
